#环境配置
spring:
  profiles:
    active: test


log:
  dev:
    fileUrl: C:\log\lms-lti-rollcall-sjtu-dev.log
    level: DEBUG
  test:
    fileUrl: /opt/lms-lti-rollcall-sjtu-test/lms-lti-rollcall-sjtu.log
    level: DEBUG


db:
  rollcall:
    dev:
      address: 172.168.70.12:65431
      username: dbuser
      password: 1q2w3e4r5t
    test:
      address: 172.168.70.227:65431
      username: dbuser
      password: 1q2w3e4r5t


redis:
  dev:
    ip: 172.168.70.12
    port: 56379
    database: 2
  test:
    ip: 172.168.70.12
    port: 56379
    database: 3


feign:
  canvas:
    dev:
      url: http://172.168.70.12:28082
      supper-admin-token: Bearer kBjFq10ipfsNTUl8y8Y3KH0gaaudS6DoeDYUWWRQYS4YmeJW5ZiGX2Skj0LU2ZA1
    test:
      url: http://172.168.70.227:28082
      supper-admin-token: Bearer lIlaLi07WNcOhXb2ig8xk6KeBjQThWWkFA7p239CZCYKvbSaQhIyfjs9sWx1JrG4
