#环境配置
spring:
  profiles:
    active: test


#自定义logging属性
logging:
  dev:
    dir-path: /root/install/service/lms-lti-rollcall-sjtu-dev/logs
  test:
    dir-path: /root/install/service/lms-lti-rollcall-sjtu-test/logs
  prod:
    dir-path: /root/install/service/lms-lti-rollcall-sjtu-prod/logs


db:
  rollcall:
    dev:
      address: 172.168.70.12:65431
      username: dbuser
      password: 1q2w3e4r5t
    test:
      address: 172.168.70.227:65431
      username: dbuser
      password: 1q2w3e4r5t


redis:
  dev:
    ip: 172.168.70.12
    port: 56379
    database: 0
  test:
    ip: 172.168.70.227
    port: 56379
    database: 0


feign:
  canvas:
    dev:
      url: http://172.168.70.12:28082
      supper-admin-token: Bearer 5Gs0WF1MeLjEoJlxlSjWFeVrrAD4AYVahVgnWD9sZncQkbU2hRS4q3BFJexeGtDx
    test:
      url: http://172.168.70.227:28082
      supper-admin-token: Bearer lIlaLi07WNcOhXb2ig8xk6KeBjQThWWkFA7p239CZCYKvbSaQhIyfjs9sWx1JrG4
